# https://docs.docker.com/compose/compose-file/

version: "3"
services:
    db:
        image: postgres:11
        environment:
            PGDATA: /mnt/db_volume/postgres_data
            POSTGRES_DB: currency_conversion_data_dev
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: secret_password
        ports:
            - "5432:5432"
        volumes:
            - ./db_volume:/mnt/db_volume:delegated
